//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWeb.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTarcker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTarcker()
        {
            this.ReturnsTrackers = new HashSet<ReturnsTracker>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int DeliveryManId { get; set; }
        public System.DateTime AssignedTime { get; set; }
        public Nullable<System.DateTime> RecievedTime { get; set; }
        public Nullable<System.DateTime> DeliveredTime { get; set; }
        public int StatusId { get; set; }
        public int RejectedByDeliveryMan { get; set; }
    
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnsTracker> ReturnsTrackers { get; set; }
    }
}
