//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWeb.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnsTracker
    {
        public int Id { get; set; }
        public string ReasonToReturn { get; set; }
        public string Method { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> DeliverymanId { get; set; }
        public System.DateTime RequestTime { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public Nullable<System.DateTime> AssignedTime { get; set; }
        public Nullable<System.DateTime> PickupTime { get; set; }
        public Nullable<System.DateTime> RecievedTime { get; set; }
        public int OrderTrackerId { get; set; }
    
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual OrderTarcker OrderTarcker { get; set; }
        public virtual Status Status { get; set; }
    }
}
